Browser=chrome
url=https://opensource-demo.orangehrmlive.com/
username=Admin
password=admin123

firstName=Kruthik
middleName=K
lastName=EK
vacancy=Software Engineer
email=kruthik@gmail.com
mobile=9876543210
filePath=C:/Users/Admin/Desktop/RESUME latest 2.pdf